# Generated by Django 6.0.1 on 2026-01-18 15:01

import django.db.models.deletion
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('url_accueil', models.URLField()),
                ('utiliser_json_ld', models.BooleanField(default=True)),
                ('selecteurs_config', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiaisonProduitConcurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_produit_concurrent', models.URLField(max_length=500)),
                ('actif', models.BooleanField(default=True)),
                ('concurrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.concurrent')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_scan', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('prix_ht_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3, null=True)),
                ('prix_ht', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=14, null=True)),
                ('prix_ttc_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3, null=True)),
                ('prix_ttc', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=14, null=True)),
                ('en_promotion', models.BooleanField(default=False)),
                ('stock_disponible', models.BooleanField(default=True)),
                ('frais_livraison_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3, null=True)),
                ('frais_livraison', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=10, null=True)),
                ('delai_livraison', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('liaison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='catalogue.liaisonproduitconcurrent')),
            ],
            options={
                'ordering': ['-date_scan'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(db_index=True, max_length=13, unique=True)),
                ('id_interne', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nom', models.CharField(max_length=255)),
                ('url_interne', models.URLField(max_length=500)),
                ('url_image_interne', models.URLField(blank=True, max_length=500, null=True)),
                ('stock_interne', models.IntegerField(default=0)),
                ('prix_achat_ht_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('prix_achat_ht', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=14)),
                ('prix_vente_ht_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro')], default='EUR', editable=False, max_length=3)),
                ('prix_vente_ht', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='EUR', max_digits=14)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalogue.marque')),
            ],
        ),
        migrations.AddField(
            model_name='liaisonproduitconcurrent',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liens_concurrents', to='catalogue.produit'),
        ),
        migrations.AlterUniqueTogether(
            name='liaisonproduitconcurrent',
            unique_together={('produit', 'concurrent')},
        ),
    ]
